# Generated by Django 5.2.8 on 2025-11-19 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'وحدة سكنية', 'verbose_name_plural': 'الوحدات السكنية'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='city',
            field=models.CharField(default='نجران', max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعّلة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم الوحدة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='سعر الليلة'),
        ),
    ]
